{
 "title": "Observability - Basic",
 "tags": [
  "observability",
  "sre"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request rate (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_requests_total{status_code=~\"5..\"}[1m])) / sum(rate(http_requests_total[status_code!~\"\"][1m])))",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}